/**
 * State machines as data, loaded from S2 (sheets 48–56).
 *
 * Two hard rules from the baseline shape this file:
 *
 *  - P-02 "Eventos, no reversas magicas": a later transition never erases that the
 *    previous state existed. So this module answers "may this transition happen", and
 *    never mutates anything. Applying a transition is a command service's job, inside a
 *    transaction that also writes the receipt, the trace and the outbox.
 *
 *  - Sheet 56: 33 transitions must be *actively* refused, and the refusal has to tell the
 *    caller what to do instead ("Camino correcto"). A generic "invalid transition" error
 *    loses the only part a user can act on, so `explain` carries `instead`.
 *
 * The dataset is generated by scripts/gen-state-machines.mjs and every record keeps its
 * source sheet and row, so a block raised at runtime can be traced to a spreadsheet row.
 */
import dataset from './generated/state-machines.json' with { type: 'json' };

export type TransitionKind = 'PERMITIDA' | 'CONDICIONAL';

export interface StateRecord {
  readonly state: string;
  readonly kind: string;
  readonly semantics: string;
  readonly terminal: boolean;
  /** Present when the source qualifies terminality, e.g. "Si operacional". */
  readonly terminal_note?: string;
  readonly source_row: number;
}

export interface TransitionRecord {
  readonly id: string;
  /** Origin states. Empty when the transition creates the aggregate (source "—"). */
  readonly from: readonly string[];
  readonly from_verbatim: string;
  readonly from_is_creation: boolean;
  readonly event: string;
  readonly to: string;
  readonly gate: string;
  readonly actor: string;
  readonly effect: string;
  readonly kind: string;
  readonly note?: string;
  readonly source_row: number;
}

export interface ProhibitedRecord {
  readonly id: string;
  readonly machine: string;
  readonly from: string;
  readonly to: string;
  readonly forbidden: string;
  readonly instead: string;
  readonly severity: string;
  readonly source_row: number;
}

export interface MachineRecord {
  readonly key: string;
  readonly domain: string;
  readonly kind: 'machine' | 'submachine';
  readonly source_sheet: string;
  readonly source_row: number;
  readonly description: string;
  readonly states: readonly StateRecord[];
  readonly transitions: readonly TransitionRecord[];
  readonly prohibited: readonly { from: string; to: string; forbidden: string; instead: string }[];
  readonly parallel_dimension_note?: string;
}

export type MachineKey =
  | 'Planificacion'
  | 'AsignacionPlanificada'
  | 'Parte'
  | 'UnidadEjecucion'
  | 'PermisoTrabajo'
  | 'DirectivaOperativa'
  | 'EventoHabilita'
  | 'CasoHabilita'
  | 'UnidadComercial'
  | 'PaqueteCertificacion'
  | 'LoteFacturacion';

const machines: readonly MachineRecord[] = dataset.machines as readonly MachineRecord[];
const prohibited: readonly ProhibitedRecord[] =
  dataset.prohibited_transitions as readonly ProhibitedRecord[];

const byKey = new Map<string, MachineRecord>(
  machines.filter((m) => m.kind === 'machine').map((m) => [m.key, m]),
);

/** Parallel dimensions (PlanificacionVersion, AccionCorrectivaHabilita, supersession). */
export const parallelDimensions: readonly MachineRecord[] = machines.filter(
  (m) => m.kind === 'submachine',
);

export const machineKeys: readonly MachineKey[] = [...byKey.keys()] as MachineKey[];

export function machine(key: MachineKey): MachineRecord {
  const found = byKey.get(key);
  if (!found) throw new Error(`Unknown state machine "${key}". Known: ${machineKeys.join(', ')}`);
  return found;
}

export function states(key: MachineKey): readonly string[] {
  return machine(key).states.map((s) => s.state);
}

export function isTerminal(key: MachineKey, state: string): boolean {
  const record = machine(key).states.find((s) => s.state === state);
  if (!record) throw new Error(`"${state}" is not a state of ${key}`);
  return record.terminal;
}

/** The canonical prohibitions (TPR-*) for one machine. */
export function prohibitions(key: MachineKey): readonly ProhibitedRecord[] {
  const name = machine(key).key;
  return prohibited.filter((p) => p.machine === name);
}

export const allProhibitions: readonly ProhibitedRecord[] = prohibited;

export type Verdict =
  | {
      readonly allowed: true;
      /** CONDICIONAL means the source itself marks the transition as conditional. */
      readonly conditional: boolean;
      readonly transition: TransitionRecord;
      /** Gate text from the sheet. The rule engine evaluates it; this is not a check. */
      readonly gate: string;
    }
  | {
      readonly allowed: false;
      readonly reason: 'PROHIBITED' | 'NO_SUCH_TRANSITION' | 'TERMINAL' | 'UNKNOWN_STATE';
      readonly message: string;
      /** What to do instead. Always present for PROHIBITED; this is the actionable part. */
      readonly instead?: string;
      readonly tpr_id?: string;
      readonly source?: string;
    };

/**
 * Can `event` move `from` → somewhere, in this machine?
 *
 * Checks, in order: the state exists; the pair is not on the TPR deny list; a transition
 * exists for this event from this state. The deny list is consulted before the allow list
 * on purpose — a prohibition must win even if a future edit to the sheets accidentally
 * introduces a transition that contradicts it.
 */
export function canTransition(key: MachineKey, from: string, event: string): Verdict {
  const m = machine(key);
  const known = new Set(m.states.map((s) => s.state));

  if (!known.has(from)) {
    return {
      allowed: false,
      reason: 'UNKNOWN_STATE',
      message: `"${from}" is not a state of ${key}. States: ${[...known].join(', ')}`,
    };
  }

  const candidate = m.transitions.find((t) => t.event === event && t.from.includes(from));

  if (!candidate) {
    const terminal = isTerminal(key, from);
    return {
      allowed: false,
      reason: terminal ? 'TERMINAL' : 'NO_SUCH_TRANSITION',
      message: terminal
        ? `${key} is in terminal state ${from}; "${event}" cannot apply. ` +
          'Terminal states preserve the object and its history (P-03): correct with an ' +
          'amendment, a new version or a supersession.'
        : `${key}: no transition for event "${event}" from ${from}`,
    };
  }

  const block = prohibitions(key).find((p) => p.from === from && p.to === candidate.to);
  if (block) {
    return {
      allowed: false,
      reason: 'PROHIBITED',
      message: `${block.id}: ${block.forbidden} (${from} → ${block.to}, ${block.severity})`,
      instead: block.instead,
      tpr_id: block.id,
      source: `56_Transiciones_Prohibidas:${block.source_row}`,
    };
  }

  return {
    allowed: true,
    conditional: candidate.kind === 'CONDICIONAL',
    transition: candidate,
    gate: candidate.gate,
  };
}

/**
 * Is this from→to pair explicitly forbidden, regardless of the event?
 * Used by DB-level and service-level guards that see a state pair, not an event.
 */
export function isProhibitedPair(key: MachineKey, from: string, to: string): ProhibitedRecord | null {
  return prohibitions(key).find((p) => p.from === from && p.to === to) ?? null;
}

/** Human-readable provenance for a machine, for trace and error messages. */
export function explain(key: MachineKey): string {
  const m = machine(key);
  return `${m.domain} · ${m.key} (${m.source_sheet}:${m.source_row}) — ${m.description}`;
}

export const master = dataset.master;
export const principles = dataset.principles;
