import { documentStore, evaluateWork } from '../intelligence/documents.js';
export function canManageDocuments(state){return state.user==='admin'||(state.user==='planner'&&state.accounts?.find(a=>a.id===state.accountId)?.permissions?.includes('documents'))}
export default {
  id:'documents',title:'Control documental',description:'Requisitos, vigencias y trabajos afectados',icon:'badge',roles:['admin','planner','operador'],contextual:true,
  render(ctx,host){const s=ctx.state(),e=ctx.esc,store=documentStore(s),manage=canManageDocuments(s);const works=host.works().filter(t=>!s.extWork||s.extWork==='all'||t.id===s.extWork);const date=s.docDate||ctx.today();const rows=works.map(work=>({work,result:evaluateWork(s,work,date,{now:ctx.today()})}));
    const input=(name,label,type='text',value='')=>`<label class="fld">${label}<input class="inp" type="${type}" name="${name}" value="${e(value)}"></label>`;
    return host.filter('documents')+`<div class="control-intro"><span class="feature-status">Evaluación documental · ${e(date)}</span><h2>Preparación para operar</h2><p>Los requisitos son configurados por la empresa. Una evidencia cargada no equivale a aprobada. La matriz pendiente no se muestra como habilitación completa; los permisos de trabajo y la disponibilidad mecánica se evalúan por separado.</p></div>
    <div class="feature-filter"><label class="fld">Fecha del trabajo<input type="date" class="inp" data-bind="s:docDate" data-rr value="${e(date)}"></label></div>
    <div class="pnl"><h3>Alertas y trabajos afectados</h3>${rows.map(({work,result})=>`<article class="feature-card"><div class="feature-meta">${e(host.workLabel(work.id))}</div><h3>${!result.known?'Matriz documental pendiente':result.blocked.length?'Requisitos críticos pendientes':'Requisitos configurados conformes'}</h3>${result.results.map(x=>`<p><span class="feature-status">${e(x.status)}</span> ${e(x.subject)} · ${e(x.requirement.title)}${x.evidence?' · vence '+e(x.evidence.validTo):''} · responsable: ${e(x.requirement.owner||'Sin asignar')}</p>`).join('')}<p class="sm">${result.known?'La evaluación cubre solamente los requisitos configurados que aplican a este trabajo.':'No hay requisitos aplicables registrados. Confirmá el alcance con control documental.'}</p></article>`).join('')||'<p class="sm">No hay trabajos en tu alcance para la selección.</p>'}</div>
    ${manage?`<div class="grid2" style="margin-top:16px"><div class="pnl"><h3>Configurar requisito</h3><form id="document-requirement" class="feature-form">${input('title','Documento / requisito')}
    <label class="fld">Tipo de recurso<select name="kind" class="inp"><option>Personal</option><option>Equipo</option></select></label>${input('subject','Persona o interno específico · vacío aplica a todos del tipo')}
    <label class="fld">Operadora<select name="operator" class="inp"><option value="">Todas</option>${Object.entries(ctx.operators).map(([k,v])=>`<option value="${k}">${e(v)}</option>`).join('')}</select></label>${input('location','Locación exacta · vacío aplica a todas')}${input('activity','Actividad exacta · vacío aplica a todas')}${input('owner','Responsable de renovación')}${input('noticeDays','Anticipación de aviso · días','number','30')}${input('maxAgeDays','Máxima antigüedad de verificación · días opcional','number')}
    <label class="fld"><span>Criticidad</span><select class="inp" name="critical"><option value="yes">Crítico para asignar</option><option value="no">Aviso</option></select></label><p class="sm">Los criterios se acuerdan con la empresa/operadora. No se crean exigencias universales ni bloqueos nuevos de envío del parte.</p><button class="btn pri">Crear requisito</button></form></div>
    <div class="pnl"><h3>Registrar evidencia y revisión</h3><form id="document-evidence" class="feature-form"><label class="fld">Requisito<select class="inp" name="requirementId">${store.requirements.filter(r=>r.active!==false).map(r=>`<option value="${e(r.id)}">${e(r.title)} · ${e(r.kind)}</option>`).join('')}</select></label>${input('subject','Persona o interno · como figura en el core')}${input('reference','Referencia al documento o sistema externo')}${input('validFrom','Vigente desde','date')}${input('validTo','Vigente hasta','date')}${input('verifiedAt','Última verificación','date',ctx.today())}<label class="fld">Resultado de revisión<select class="inp" name="status"><option>Pendiente de validación</option><option>Aprobado</option><option>Rechazado</option></select></label>${input('note','Observación de revisión')}<button class="btn pri">Guardar evidencia</button><p class="sm">Se registra una nueva versión con responsable y fecha. No hay conexión a portales de terceros ni envío automático de notificaciones fuera de la app.</p></form></div></div>
    <div class="pnl" style="margin-top:16px"><h3>Matriz y evidencias registradas</h3>${store.requirements.map(r=>`<article class="feature-card"><h3>${e(r.title)} · ${e(r.kind)}</h3><p>${r.operator?e(ctx.operators[r.operator]):'Todas las operadoras'} · ${r.critical?'Crítico':'Aviso'} · ${e(r.owner)} · aviso ${e(r.noticeDays)} días</p><button class="btn sm2" data-a="document-toggle" data-id="${e(r.id)}">${r.active===false?'Reactivar':'Desactivar requisito'}</button>${store.evidence.filter(x=>x.requirementId===r.id).map(x=>`<p class="sm">${e(x.subject)} · ${e(x.status)} · ${e(x.validFrom)} → ${e(x.validTo)} · ${e(x.reference)} · revisión ${e(x.reviewedBy)}</p>`).join('')}</article>`).join('')||'<p class="sm">Sin requisitos. Las habilitaciones de la base original se conservan en su pantalla.</p>'}</div>`:''}`;
  }
};
