import { operationMetrics } from '../intelligence/operations.js';
const datePlus=(date,n)=>new Date(Date.parse(date)+n*86400000).toISOString().slice(0,10);
export default {
  id:'operations',title:'Centro de control operativo',description:'Cuenca Golfo San Jorge · análisis para planificación',icon:'chart',roles:['planner'],contextual:false,
  render(ctx){const s=ctx.state(),e=ctx.esc,today=ctx.today();const from=s.opsFrom||datePlus(today,-6),to=s.opsTo||datePlus(today,7);if(from>to||!Number.isFinite(Date.parse(from))||!Number.isFinite(Date.parse(to))||(Date.parse(to)-Date.parse(from))/86400000>366)return '<div class="pnl">Elegí un rango válido de hasta un año. <button class="btn" data-a="ops-reset">Restablecer filtros</button></div>';
    const m=operationMetrics(s,{from,to,today,operator:s.opsOperator||'all',resource:s.opsResource||'all',location:s.opsLocation||'all',includeExamples:s.opsExamples==='yes'});const hours=n=>(Number(n||0)/60).toFixed(1)+' h';
    const selector=(key,label,options)=>`<label class="fld">${label}<select class="inp" data-bind="s:${key}" data-rr>${options.map(([v,l])=>`<option value="${e(v)}" ${s[key]===v?'selected':''}>${e(l)}</option>`).join('')}</select></label>`;
    const locations=[...new Set(s.trabajos.map(t=>t.yac+' · '+t.pozo))];
    return `<div class="control-intro"><span class="feature-status">Planner · ${s.opsExamples==='yes'?'modo exploración con ejemplos':'registros cargados'}</span><h2>Preparar, ejecutar y aprender de cada jornada</h2><p>Las sugerencias son reglas explicables basadas en los registros seleccionados. No calculan ahorros ni autorizan condiciones de seguridad. ${s.opsExamples==='yes'?'Incluye datos de ejemplo o heredados: no representa desempeño real.':'Los registros de ejemplo y sin procedencia se excluyen.'}</p></div>
    <div class="feature-filter"><label class="fld">Desde<input type="date" class="inp" value="${from}" data-bind="s:opsFrom" data-rr></label><label class="fld">Hasta<input type="date" class="inp" value="${to}" data-bind="s:opsTo" data-rr></label>${selector('opsOperator','Operadora',[['all','Todas'],...Object.entries(ctx.operators)])}${selector('opsResource','Recurso',[['all','Todos'],...ctx.resources.map(r=>[r.id,r.n])])}${selector('opsLocation','Locación',[['all','Todas'],...locations.map(x=>[x,x])])}${selector('opsExamples','Fuente',[['no','Solo registros cargados'],['yes','Explorar con ejemplos']])}</div>
    <div class="dtiles">${[['Cobertura de partes',m.coverage===null?'Sin base':m.coverage+'%',m.submitted+' de '+m.expected+' jornadas esperadas hasta hoy'],['Tiempo operativo',hours(m.categories.op),'Duración de actividades · no horas hombre'],['Demoras y viento',hours((m.categories.es||0)+(m.categories.vi||0)),'Ver causas y acciones'],['Horas hombre',m.peopleHours.toFixed(1)+' h','Personal presente · horarios registrados']].map(([a,b,c])=>`<div class="dtile"><span>${a}</span><b>${b}</b><small>${e(c)}</small></div>`).join('')}</div>
    <div class="grid2"><div class="pnl"><h3>Composición del tiempo registrado</h3>${[['op','Operación'],['tr','Traslado'],['es','Espera'],['vi','Parada por viento'],['rf','Refrigerio']].map(([key,label])=>`<div class="control-bar"><span>${label}</span><meter min="0" max="${Math.max(m.totalMinutes,1)}" value="${m.categories[key]||0}" aria-label="${label}"></meter><b>${hours(m.categories[key])}</b></div>`).join('')}<p class="sm">${m.usable.length} partes enviados, observados, aprobados o certificados. Datos provisionales; ${m.overlaps} partes con superposición excluidos de los cálculos de tiempo y producción.</p></div><div class="pnl"><h3>Producción por actividad y unidad</h3><table class="tbl"><thead><tr><th>Actividad</th><th>Unidad</th><th class="num">Cantidad</th></tr></thead><tbody>${m.production.map(r=>`<tr><td>${e(r.activity)}</td><td>${e(r.unit)}</td><td class="num">${e(r.quantity)}</td></tr>`).join('')||'<tr><td colspan="3">Sin cantidades registradas</td></tr>'}</tbody></table><p class="sm">No se suman unidades diferentes ni se interpreta lo producido como importe certificable.</p></div></div>
    <div class="grid2" style="margin-top:16px"><div class="pnl"><h3>Preparación de trabajos próximos</h3>${m.readiness.map(({work,docs,reservations})=>`<article class="feature-card"><div class="feature-meta">${e(work.id)} · ${e(work.yac)} · ${e(work.pozo)}</div><h3>${docs.blocked.length?'Requisitos pendientes':docs.known?'Documentación evaluada':'Matriz documental pendiente'}</h3><p>${docs.blocked.length} requisitos críticos pendientes · ${docs.warnings.length} avisos hasta el cierre previsto · ${reservations.length} pedidos de materiales</p><div class="feature-toolbar"><button class="btn sm2" data-a="t-open" data-id="${e(work.id)}">Ver trabajo</button><button class="btn sm2" data-a="module-open" data-module="documents" data-work="${e(work.id)}">Revisar documentación</button></div></article>`).join('')||'<p class="sm">Sin trabajos próximos para estos filtros.</p>'}</div><div class="pnl"><h3>Sugerencias de eficiencia y continuidad</h3>${m.recommendations.map(r=>`<article class="feature-card"><span class="feature-status">${e(r.kind)}</span><h3>${e(r.title)}</h3><p><b>Evidencia:</b> ${e(r.evidence)}</p><p>${e(r.action)}</p>${r.workId?`<button class="btn sm2" data-a="t-open" data-id="${e(r.workId)}">Abrir trabajo afectado</button>`:''}</article>`).join('')||'<p class="sm">Todavía no hay evidencia suficiente para sugerir intervenciones.</p>'}</div></div>
    <div class="pnl" style="margin-top:16px"><h3>Lectura del circuito</h3><div class="stats">${[['En revisión','env'],['Observados','obs'],['Para certificar','apr'],['Certificados','cert']].map(([label,key])=>`<div class="stat"><b>${m.parts.filter(p=>p.estado===key).length}</b><span>${label}</span></div>`).join('')}</div><p>Mediana de aprobación: ${m.approval.median===null?'Sin medición':m.approval.median.toFixed(1)+' h'} (${m.approval.count} registros) · mediana de certificación: ${m.certification.median===null?'Sin medición':m.certification.median.toFixed(1)+' h'} (${m.certification.count} registros).</p><p class="sm">No se estiman tiempos de aprobación de registros antiguos sin marcas temporales normalizadas. Pronóstico meteorológico, distancias, ventanas de ingreso y tarifas están pendientes de fuentes verificadas.</p></div>`;
  }
};
