import { productMetrics, productInsights } from '../intelligence/telemetry.js';
export default {
  id:'product',title:'Centro de control de la app',description:'Experiencia de uso y confiabilidad · administración',icon:'cog',roles:['admin'],contextual:false,
  render(ctx){const s=ctx.state(),e=ctx.esc;const m=productMetrics(s,{from:s.productFrom||'',to:s.productTo||'9999-12-31'});const fmt=n=>n===null?'Sin medición':Math.round(n)+' s';
    const steps=['Inicio','Personal','Equipos','Tareas','Cierre'];const sections=[...steps.map((label,i)=>[String(i),label]),['quick','Resumen rápido']];const total=Object.values(m.steps).reduce((a,b)=>a+b,0);const opportunities=s.productOpportunities||[];const insights=productInsights(s);
    return `<div class="control-intro"><span class="feature-status">Producto · datos de uso local</span><h2>Mejorar la aplicación con evidencia</h2><p>Esta vista mide el software. Los indicadores operativos pertenecen al centro del planner. La medición empieza al utilizar esta versión; los partes de ejemplo no generan tiempos ficticios.</p></div>
    <div class="feature-filter"><label class="fld">Desde<input class="inp" type="date" data-bind="s:productFrom" data-rr value="${e(s.productFrom)}"></label><label class="fld">Hasta<input class="inp" type="date" data-bind="s:productTo" data-rr value="${e(s.productTo)}"></label></div>
    <div class="dtiles">${[['Mediana observada',fmt(m.median),'Tiempo observado por envío'],['P90 observado',fmt(m.p90),'90 % de las mediciones finalizadas'],['Dentro de 2 minutos',m.within120===null?'Sin medición':m.within120+'%',m.completed+' envíos medidos · incluye reenvíos'],['Fallos detectados',m.errors,'Guardado y ejecución en este dispositivo']].map(([a,b,c])=>`<div class="dtile"><span>${a}</span><b>${b}</b><small>${e(c)}</small></div>`).join('')}</div>
    <div class="grid2"><div class="pnl"><h3>Fricción por sección</h3>${sections.map(([i,label])=>{const value=m.steps[i]||0;return `<div class="control-bar"><span>${label}</span><meter min="0" max="${Math.max(total,1)}" value="${value}" aria-label="${label}: ${Math.round(value/1000)} segundos"></meter><b>${Math.round(value/1000)} s</b></div>`}).join('')}<p class="sm">Tiempo observado entre interacciones. Se excluyen pausas mayores a 30 s y pestañas ocultas; no equivale a un estudio de tiempos completo.</p></div>
    <div class="pnl"><h3>Calidad de la medición</h3><dl class="kv"><dt>Inicio de cobertura</dt><dd>${m.coverage?e(new Date(m.coverage).toLocaleString('es-AR')):'Todavía sin eventos'}</dd><dt>Sesiones iniciadas</dt><dd>${m.sessions}</dd><dt>Sesiones sin envío</dt><dd>${m.inProgress} · no se clasifican como abandono</dd><dt>Intentos con validaciones</dt><dd>${m.blocks}</dd><dt>Alcance</dt><dd>Este navegador · sin agregación entre empresas o dispositivos</dd></dl><p class="sm">No se almacenan textos ingresados, contraseñas ni fotos en telemetría. Esta medición parcial no demuestra por sí sola el cumplimiento del objetivo de dos minutos. Una muestra pequeña no justifica prometer ahorros.</p></div></div>
    <div class="pnl" style="margin-top:16px"><h3>Señales para mejorar la aplicación</h3>${insights.map(r=>`<article class="feature-card"><span class="feature-status">${e(r.priority)}</span><h3>${e(r.title)}</h3><p>${e(r.evidence)}</p><p>${e(r.hypothesis)}</p><button class="btn sm2" data-a="product-propose" data-id="${r.id}">Pasar a oportunidades</button></article>`).join('')||'<p class="sm">Sin señales suficientes para priorizar mejoras. La meta de dos minutos aún debe validarse con operarios reales.</p>'}</div>
    <div class="pnl" style="margin-top:16px"><h3>Uso observado de módulos</h3>${Object.entries(m.events.filter(x=>x.type==='action'&&(x.module||x.target?.startsWith('x-'))).reduce((a,x)=>{const key=x.module||x.target.slice(2);a[key]=(a[key]||0)+1;return a},{})).map(([key,n])=>`<p>${e(key)} · ${n} aperturas / acciones</p>`).join('')||'<p class="sm">Todavía sin uso registrado de módulos.</p>'}</div>
    <div class="grid2" style="margin-top:16px"><div class="pnl"><h3>Oportunidad de mejora del producto</h3><form id="product-opportunity" class="feature-form"><label class="fld">Problema observado<input class="inp" name="title" required></label><label class="fld">Evidencia y período<textarea class="inp" name="evidence" required></textarea></label><label class="fld">Hipótesis / beneficio esperado<textarea class="inp" name="hypothesis" required></textarea></label><label class="fld">Responsable<input class="inp" name="owner" required></label><label class="fld">Esfuerzo estimado<select class="inp" name="effort"><option>Por evaluar</option><option>Bajo</option><option>Medio</option><option>Alto</option></select></label><button class="btn pri">Registrar oportunidad</button></form></div>
    <div class="pnl"><h3>Mejoras en evaluación</h3>${opportunities.map(r=>`<article class="feature-card"><div class="feature-meta">${e(r.status)} · ${e(r.owner)} · esfuerzo ${e(r.effort)}</div><h3>${e(r.title)}</h3><p><b>Evidencia:</b> ${e(r.evidence)}</p><p><b>Hipótesis:</b> ${e(r.hypothesis)}</p><form data-product-update="${e(r.id)}" class="feature-form"><label class="fld">Estado<select class="inp" name="status">${['Por evaluar','Priorizada','En desarrollo','Implementada','Descartada'].map(x=>`<option ${x===r.status?'selected':''}>${x}</option>`).join('')}</select></label><label class="fld">Resultado medido después del cambio<textarea class="inp" name="result">${e(r.result||'')}</textarea></label><button class="btn sm2">Guardar seguimiento</button></form></article>`).join('')||'<p class="sm">Registrá oportunidades con evidencia; no se crean recomendaciones de producto a partir de registros operativos de ejemplo.</p>'}</div></div>`;
  }
};
