import { evaluateWork } from './documents.js';
export function minutes(a,b){if(!/^\d{2}:\d{2}$/.test(a||'')||!/^\d{2}:\d{2}$/.test(b||''))return 0;const val=t=>Number(t.slice(0,2))*60+Number(t.slice(3));const delta=val(b)-val(a);return delta<0?delta+1440:delta}
export function overlappingIntervals(regs){const spans=regs.filter(r=>r.de&&r.a).map(r=>{const start=Number(r.de.slice(0,2))*60+Number(r.de.slice(3));return [start,start+minutes(r.de,r.a)]});return spans.some((a,i)=>spans.slice(i+1).some(b=>[-1440,0,1440].some(offset=>a[0]<b[1]+offset&&a[1]>b[0]+offset)))}
export function operationMetrics(state,{from,to,operator='all',resource='all',location='all',includeExamples=false,today}){
  const matches=t=>(operator==='all'||(t.op||state.contratos[t.ct]?.op)===operator)&&(resource==='all'||t.rec===resource)&&(location==='all'||t.yac+' · '+t.pozo===location)&&(includeExamples||t.dataOrigin==='recorded');
  const works=state.trabajos.filter(matches);const ids=new Set(works.map(t=>t.id));const parts=state.partes.filter(p=>ids.has(p.pl)&&p.fecha>=from&&p.fecha<=to&&(includeExamples||p.dataOrigin==='recorded'));
  const categories={},waits={},production={},byDay={};let peopleHours=0,overlaps=0;
  const usable=parts.filter(p=>p.ejec&&['env','obs','apr','cert'].includes(p.estado));
  for(const p of usable){const regs=p.ejec.reg||[];const ordered=[...regs].sort((a,b)=>(a.de||'').localeCompare(b.de||''));if(overlappingIntervals(ordered)){overlaps++;continue}
    for(const r of regs){const duration=minutes(r.de,r.a);categories[r.c]=(categories[r.c]||0)+duration;byDay[p.fecha]=(byDay[p.fecha]||0)+duration;if(r.c==='es')waits[r.d||'Sin motivo']=(waits[r.d||'Sin motivo']||0)+duration;if(r.c==='op'&&r.d&&Number(r.q)>0){const key=r.d+'|'+r.u;production[key]??={activity:r.d,unit:r.u,quantity:0};production[key].quantity+=Number(r.q)}}
    for(const person of p.ejec.personal||[])if(person.pres)peopleHours+=minutes(person.base,person.out)/60;
  }
  let expected=0,submitted=0;for(const t of works){for(let day=from;day<=to&&day<=today;day=new Date(Date.parse(day)+86400000).toISOString().slice(0,10)){const end=new Date(Date.parse(t.inicio)+(t.dias-1)*86400000).toISOString().slice(0,10);if(day>=t.inicio&&day<=end&&(!t.cierre||day<=t.cierre.fecha)){expected++;if(parts.some(p=>p.pl===t.id&&p.fecha===day&&['env','obs','apr','cert'].includes(p.estado)))submitted++}}}
  const upcoming=works.filter(t=>!t.cierre&&t.inicio<=to&&new Date(Date.parse(t.inicio)+(t.dias-1)*86400000).toISOString().slice(0,10)>=today);
  const readiness=upcoming.map(t=>({work:t,docs:evaluateWork(state,t,new Date(Date.parse(t.inicio)+(t.dias-1)*86400000).toISOString().slice(0,10),{now:today}),reservations:(state.extensions?.records.materials||[]).filter(r=>r.workId===t.id)}));
  const recommendations=[];
  for(let i=0;i<upcoming.length;i++)for(let j=i+1;j<upcoming.length;j++){const a=upcoming[i],b=upcoming[j],end=t=>new Date(Date.parse(t.inicio)+(t.dias-1)*86400000).toISOString().slice(0,10);if(a.inicio<=end(b)&&b.inicio<=end(a)&&(a.rec===b.rec||(a.pers||[]).some(x=>(b.pers||[]).includes(x))||(a.eqs||[]).some(x=>(b.eqs||[]).includes(x))))recommendations.push({title:'Revisar asignaciones · '+a.id+' / '+b.id,evidence:'Recurso, personal o equipo compartido en fechas superpuestas',action:'Confirmar ventanas y disponibilidad antes de mantener ambas asignaciones. La coincidencia de días no prueba por sí sola un conflicto horario.',kind:'Asignaciones',workId:a.id})}

  for(const [cause,value]of Object.entries(waits).sort((a,b)=>b[1]-a[1]).slice(0,3))recommendations.push({title:'Revisar espera: '+cause,evidence:(value/60).toFixed(1)+' h en el período',action:/permiso|responsable/i.test(cause)?'Coordinar ventana de firma e ingreso con la operadora antes de movilizar.':/material/i.test(cause)?'Confirmar reserva y disponibilidad de retiro antes de la salida.':'Revisar el motivo y coordinar una acción con el responsable.',kind:'Espera'});
  if(categories.tr)recommendations.push({title:'Revisar traslados por locación',evidence:(categories.tr/60).toFixed(1)+' h registradas en traslados',action:'Comparar trabajos equivalentes por locación y evaluar secuencia de visitas. No hay distancias ni rutas verificadas para calcular un ahorro.',kind:'Traslado'});
  if(categories.vi)recommendations.push({title:'Analizar las paradas por viento',evidence:(categories.vi/60).toFixed(1)+' h registradas por viento',action:'Revisar exposición de actividades y ventanas de trabajo con el procedimiento aprobado. Sin pronóstico conectado ni umbral universal.',kind:'Viento'});
  for(const row of readiness){if(row.docs.blocked.length)recommendations.push({title:'Requisitos pendientes · '+row.work.id,evidence:row.docs.blocked.length+' requisitos críticos sin conformidad',action:'Gestionar evidencia o reasignar recursos antes de movilizar.',kind:'Documentación',workId:row.work.id});if(row.reservations.some(r=>!['Retirado','Cerrado','Cancelado'].includes(r.status)))recommendations.push({title:'Materiales pendientes · '+row.work.id,evidence:'Pedido / reserva todavía sin retiro completo',action:'Confirmar código, cantidades y retiro con la operadora.',kind:'Materiales',workId:row.work.id})}
  const median=values=>values.length?(()=>{const a=[...values].sort((x,y)=>x-y),i=Math.floor(a.length/2);return a.length%2?a[i]:(a[i-1]+a[i])/2})():null;const approval=parts.filter(p=>p.submittedAt&&p.approvedAt&&Date.parse(p.approvedAt)>=Date.parse(p.submittedAt)).map(p=>(Date.parse(p.approvedAt)-Date.parse(p.submittedAt))/3600000);const certification=parts.filter(p=>p.approvedAt&&p.certifiedAt&&Date.parse(p.certifiedAt)>=Date.parse(p.approvedAt)).map(p=>(Date.parse(p.certifiedAt)-Date.parse(p.approvedAt))/3600000);
  return {approval:{median:median(approval),count:approval.length},certification:{median:median(certification),count:certification.length},works,parts,usable,categories,waits,production:Object.values(production),peopleHours,overlaps,expected,submitted,coverage:expected?Math.round(submitted/expected*100):null,readiness,recommendations,byDay,totalMinutes:Object.values(categories).reduce((a,b)=>a+b,0)};
}
